### ISSUE TITLE
Allow user to choose which cache to use on-request

### ISSUE THREAD

**Issue by DanAtkinson** [Dbz/WebCache#1]
I'd like to be able to click the button and choose to either open in Google's cache, Wayback machine, Coral etc rather than it just attempt the page in the first selected one.

Another problem is that, sometimes, I want to a see a previous version of a page, but I am seemingly unable to do that if the origin page is still up.

**Comment by Dbz** [comment]
Hey Dan,

Thank you for making an issue. I think some other people might want this feature too, so I'll get started on building it. I need to design the options page to allow selecting which caches appear in the right-click menu.

**Comment by Dbz** [comment]
@DanAtkinson good news! I added the option to choose which cache to use via right click context menus. If you go to the extensions page, you can click update extensions, and you will see the new version! Unfortunately, I haven't fixed your second issue yet.

**Comment by Dbz** [comment]
@DanAtkinson can you give me steps to reproduce your second bug?

**Comment by DanAtkinson** [comment]
@Dbz I'm afraid that I can't remember the original steps to reproduce the issue. I think it should be okay to close this issue now though.

Thanks for adding the context menu functionality!

**Comment by Dbz** [comment]
My pleasure! Please remember to rate WebCache if you like it!
