### ISSUE TITLE
The chrome extension is broken.

### ISSUE THREAD

**Issue by hunterforcode** [Dbz/WebCache#4]
Hi, thank you for providing an excellent extension.
I install the extension from the chrome store https://chrome.google.com/webstore/detail/webcache/cmmlgikpahieigpcclckfmhnchdlfnjd

But as you know, when I try to use it, the extension is broken. As a result, I try to fix the extension by clicking the repair button, however, this problem appears again while I endeavor to use it. It is just like a loop without ending. 

My Desktop Environment is Ubuntu 14.04 64-Bit and the corresponding version of google chrome browser is 61.0.3163.79. If some details helpful to resolve the problem are missed out here, please feel free to put them forward.

**Comment by Dbz** [comment]
Hello hunter, what do you mean the extension is broken? Can you provide a screen shot?

**Comment by Dbz** [comment]
I just tested. I have no idea how this got into the chrome store. I'll update the extension asap

**Comment by hunterforcode** [comment]
Hi, I reopen this issue due to the similar bug of this extension.
Here is how to produce in my Ubuntu 14.04 64-Bit desktop environment:
1. click the webcache icon in chrome extension icon and it works smoothly
2. right-click webcache icon and click the option column, the extension is broken again as the situation above.  (As a result, I try to fix the extension by clicking the repair button, however, this problem appears again while I endeavor to use it. It is just like a loop without ending.)

**Comment by Dbz** [comment]
Hey @hunterforcode what version of WebCache are you using?

**Comment by hunterforcode** [comment]
Latest version from chrome store v4.1.0

**Comment by Dbz** [comment]
The latest version in the chrome store is actually v4.1.1

**Comment by hunterforcode** [comment]
Ok, let me try it again. The same problem here.

**Comment by Dbz** [comment]
What's your version of chrome?

**Comment by hunterforcode** [comment]
The same as the first post.

**Comment by Dbz** [comment]
Is that the latest version of chrome? Thank you for bearing with me here. This appears to be a linux specific issue

**Comment by hunterforcode** [comment]
Yes. It doesn't matter. I only test it in Linux desktop environment.

**Comment by UMLAUTaxl** [comment]
Hi, I'm also on Linux and have this problem. But other extensions' options work just fine. 
They open chrome-extension://$hash/data/settingsPanel.html?panel=settings
or
chrome-extension://$hash/options.html

WebCache Version: 4.1.1
google-chrome-stable      64.0.3282.167-1 amd64

**Comment by Dbz** [comment]
@UMLAUTaxl are you having the exact same problem?:

```
1) click the webcache icon in chrome extension icon and it works smoothly
2) right-click webcache icon and click the option column, the extension is broken again as the situation above. (As a result, I try to fix the extension by clicking the repair button, however, this problem appears again while I endeavor to use it. It is just like a loop without ending.)
```

**Comment by UMLAUTaxl** [comment]
@Dbz Yes, exactly like that. On 1) it opens Google's webcache but that's not really what I want from this extension.
